version: '3.5'

services:
  symfony-platform-nginx:
    container_name: symfony-platform-nginx
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 250:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - symfony-platform-be
    networks:
      - symfony-platform-network

  symfony-platform-be:
    container_name: symfony-platform-be
    build:
      context: docker/php
      args:
        UID: $U_ID

    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=Docker
    volumes:
      - ./:/appdata/www
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - symfony-platform-db
    networks:
      - symfony-platform-network

  symfony-platform-db:
    container_name: symfony-platform-db
    image: mysql:8.0
    ports:
      - 36000:3306
    environment:
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - symfony-platform-db-data:/var/lib/mysql
    networks:
      - symfony-platform-network

volumes:
  symfony-platform-db-data:

networks:
  symfony-platform-network:
    external: true